name: Publish
on: [push, pull_request]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
